### ISSUE TITLE
can not get frames when use python3 to run depth_map_runner.py

### ISSUE THREAD

**Issue by penglaige** [Microsoft/malmo#711]
I updated my malmo to 0.35.6 version and tried to run depth_map_runner.py by python3.
But it didn't work very well, seems that the agent can not get frames from the video.
What's the problem with it?

INFO:__main__:Mission 0
INFO:__main__:Waiting for the mission to start
.......................................................................................................................................
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Got frame!
INFO:__main__:d2v, dv, v: 0, -1, 0
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...
INFO:__main__:Waiting for frames...

**Comment by AndKram** [comment]
What OS are you on? Did the Minecraft mission fail to load or visibly hang?

**Comment by penglaige** [comment]
macos high sierra version10.13.4, the agent got a few frames every time at the beginning of each mission and then got nothing, and at the end of the mission it said 'got frame' and then the mission stopped, I don't know what's the problem.

**Comment by AndKram** [comment]
I believe it's fixed by the "safewrite" branch. You could try that while we get the fix into master.

**Comment by penglaige** [comment]
I tried it but still the same problem. 
At first it can get several frames and then the video stopped, after about 10 seconds the agent began to turn around at the same place. 
I tested the videoproducer on another simple mission(with discrete command move and turn), it worked well for most of time but some times the same problem occurred.

```
    while world_state.number_of_video_frames_since_last_state < 1 and world_state.is_mission_running:
        world_state = agent_host.getWorldState()
        print("Waiting for frames...")
        time.sleep(0.05)
        world_state = agent_host.getWorldState()

    print("Got frame!")

    agent_host.sendCommand("move 1")
    time.sleep(0.05)
    agent_host.sendCommand("turn 1")
    time.sleep(0.05)
```
By changing the sleep time can solve the problem to some extent, but this didn't work on the depth_map_runner problem.

**Comment by AndKram** [comment]
0.36 release addressed comms issues on MacOS. Test is passing for me.
